local Remap = require("user.keymaps")
local nnoremap = Remap.nnoremap

-- nnoremap("<C-p>", ":Telescope")
nnoremap("<leader>ps", function()
	require("telescope.builtin").grep_string({ search = vim.fn.input("Grep For > ") })
end)
nnoremap("<C-g>", function()
	require("telescope.builtin").git_files()
end)
nnoremap("<Leader>pf", function()
	require("telescope.builtin").find_files()
end)

nnoremap("<leader>pw", function()
	require("telescope.builtin").grep_string({ search = vim.fn.expand("<cword>") })
end)
nnoremap("<leader>pb", function()
	require("telescope.builtin").buffers()
end)
nnoremap("<leader>vh", function()
	require("telescope.builtin").help_tags()
end)
nnoremap("<leader>vrc", function()
	require("user.telescope").search_dotfiles({ hidden = true })
end)
nnoremap("<leader>lg", function()
	require("telescope.builtin").live_grep({ grep_open_files = true })
end)
